totalEpoch: 1200
startEpoch: 1
lr: 0.003
factor: 0.9

lossModel:
  model:
    heed:
      in_channel: 3
      layer_num: 3

  loss:
    heed:
#      ratio: 3.
      eps: !!float '1e-6'

score:
  totalBox: 1000
  edgeThresh: 5
  probThresh: 0.3
  scoreThresh: 0.7
  label: 'binaryMap'

accurancy:
  scoreThresh: 0.7
  ignoreThresh: 0.5
  accThresh: 0.5

train:
  batchSize: 8
  numWorkers: 2
  dropLast: True
  shuffle: True
  pinMemory: False
  dataset:
    imgType: 0
    imgDir: 'train/image'
    maskDir: 'train/mask'
    tarFile: 'train/target.json'
    prep:
      DetAug:
        onlyResize: False
        Fliplr:
          p: 0.5
        Affine:
          rotate: [ -10, 10 ]
          fit_output: True
        Resize:
          size: [ 0.5, 3. ]
      DetCrop:
        minCropSize: 0.1
        maxTries: 10
        generalSize: [ 640, 640 ]
      DetForm:
        shrinkRatio: 0.4
      DetNorm:
        mean: [ 122.67891434, 116.66876762, 104.00698793 ]
      DetFilter:
        key: [ 'polygon', 'shape', 'ignore', 'train' ]

valid:
  batchSize: 4
  numWorkers: 2
  dropLast: False
  shuffle: False
  pinMemory: False
  dataset:
    imgType: 0
    imgDir: 'valid/image'
    maskDir: 'valid/mask'
    tarFile: 'valid/target.json'
    prep:
      DetAug:
        onlyResize: True
        Resize:
          size: { "height": 640, "width": 640 }
      DetForm:
        shrinkRatio: 0.4
      DetNorm:
        mean: [ 122.67891434, 116.66876762, 104.00698793 ]
      DetFilter:
        key: [ 'polygon', 'shape', 'ignore', 'train' ]

optimizer:
  name: Adam
  args:
    betas: [ 0.9, 0.999 ]
    eps: !!float '1e-8'

checkpoint:
  workspace: 'checkpoint'
  resume: ''

logger:
  workspace: 'logger'
  level: INFO
